//
//  ShoeData.swift
//  Shoe-Shock
//
//  Created by Care Farrar on 1/29/21.
//

import Foundation
class SHOES {
    static let Data = SHOES()
    var Nike = [
        Shoe(image: "Nike-Air-Flex", brand: "Nike", condition: "New", name: "Air Flex", price: 160, discrip: " The Nike Air Flex  shoes are lightwight, streamlined, and comfortable for all-day style and comfort. \n FlyKnitFlyknit technology is stretchy, snug, and breathable for cool, soft comfort. In addition, the Flyknit in this version has been improved to be stronger and more durable. Nike React foam cushioning is wider and stacked higher for an extra plush feel underfoot and reliable shock absorption.Less material between foot and midsole for a softer, more responsive feel. More rubber in the outsole is designed to provide better traction and durability. Run Fearless"),
        Shoe(image: "Nike-Air-Monarch", brand: "Nike", condition: "New", name: "Air Monarch", price: 60, discrip: "Fly through your workout in these Nike Air cross-trainers. The mesh tongue and lining offer breathability, while the pivot-point on the outsole gives you traction on any surface. From the treadmill to the pavement, you'll love exercising in these men's Nike Air Monarch VI cross-trainers.SHOE FEATURES Air-Sole unit provides excellent cushioning. Phylon midsole absorbs shock. Grooved rubber outsole ensure flexibility. SHOE CONSTRUCTION Leather upper Mesh lining Phylon midsole Rubber outsole SHOE DETAILS Lace up closure Padded footbed"),
        Shoe(image: "Nike-Air-Touch", brand: "Nike", condition: "New", name: "Air Touch", price: 85, discrip: "Low-top design for added mobilityFull-length BRS 1000® carbon fiber rubber Waffle outsole for durability and tractionPhylon forefoot provides a great toe-offBreathable mesh uppers with synthetic overlays provide ventilation and supportReflective elements help ensure visibility in low lightPadded tongue and collarMolded EVA sock liners offer comfort and support underfootPhylon midsoles with visible Max Air units in the heels provide lightweight cushioningLace-up front locks you in for a secure fit")
    ]
    var Addidas: [Shoe] = [
        Shoe(image: "Adidas-Cloud-Boost", brand: "Addias", condition: "New", name: "Cloud Boost", price: 120, discrip: "ZX takes an icon to a new dimension of comfy. Innovated for the ultimate squish with new wrapped BOOST, ZX never felt so good. A springy Boost midsole swaddled in a wrap-around gradient. A progressive look and technical design, brimming with Boost. Feels too good to be explained."),
        Shoe(image: "Adidas-Light-Racer", brand: "Addias", condition: "New", name: " Light Racer", price: 60, discrip: "Explore the landscape in clean style and supreme comfort. The minimalist X_PLR shoes for men keep the look sleek and simple. The lightweight, mesh-lined knit upper is accented with nubuck overlays and a contrast saddle that integrates with the speed lacing system."),
        Shoe(image: "Adidas-PureMotion", brand: "Addias", condition: "New", name: "PureMotion", price: 70, discrip: "It's a busy day ahead. Match your get-it-done attitude with running-inspired, comfort-driven style. These adidas sneakers bring a cushioned, foot-hugging feel to everything on your to-do list. Lace up and get to it."),
        Shoe(image: "Adidas-Questar-Flow", brand: "Addias", condition: "New", name: "Questar Flow", price: 150, discrip: "Stretchy knit upper is breathable and comfortable Lace-up closure and sock-like fit Mug guard overlays wrap the foot BOOST midsole with EVA plugs for a classic look Continental Rubber outsole with exaggerated lugs for grippy traction The adidas Originals NMD R1 Trail is imported. Built for the road less traveled, the Men's adidas Originals NMD R1 Trail Running Shoes offer up the same energy return as before, now with additional grip and traction for the trails.")
    ]
    var Jordan: [Shoe] = [
        Shoe(image: "Jordan-Retro", brand: "Jordan", condition: "New", name: "Retro OG", price: 289, discrip: "The Air Jordan 4 Retro OG 'Fire Red' 2020 released in 2020, bringing back the OG colorway of the silhouette. The shoe's upper is built with white leather, accented by hits of Fire Red throughout, including the signature eyelets. Underfoot, the midsole houses visible Air in the heel for cushioning, while a Nike Air logo on the heel completes the throwback look."),
        Shoe(image: "Jordan-Dunk-Low", brand: "Jordan", condition: "New", name: "Dunk-Low", price: 250, discrip: "The Dunk Low 'Black White' brings a classic two-tone look to its classic basketball construction. The shoe's low-top build emerges in leather, with a white base contrasted by black overlays, with further black on the Swoosh branding. Perforations on the toe box provide breathability, while underfoot, the two-tone look is matched by the tooling, which incorporates a concentric rubber outsole for traction.")
    ]
    var Puma: [Shoe] = [
        Shoe(image: "Fastest-Furver-Puma", brand: "Puma", condition: "New", name: "Fast-Futurver", price: 110, discrip: "Bulky retro RS silhouette Textile upper with synthetic leather overlays Reflective overlays on quarter panel, heel and tongue Full lace closure PU midsole for lightweight cushioning and comfort Rubber outsole provides durable grip and traction PUMA Cat Logo print at lateral side Glossy TPU piece at heel Lenticular tongue label with PUMA branding Webbing pull loop at heel"),
        Shoe(image: "RS-Curve-Puma", brand: "Puma", condition: "New", name: "RS-Curve", price: 10, discrip: "Bulky RS silhouette Mesh upper with leather and suede overlays Full lace closure with extended lockdown Wavy, sculpted platform midsole design Soft PU midsole for lightweight cushioning Rubber outsole for durable grip and traction PUMA Formstrip overlay at sides Webbing pull loops at heel and tongue 3D heel piece"),
        Shoe(image: "Fast-Wild-Disco-Puma", brand: "Puma", condition: "New", name: "Fast-Wild-Disco", price: 110, discrip: "Bulky retro RS silhouetteLeather upper with snakeskin-printed panelsFull lace closureSoft padded collar and tongueLightweight cushioned midsole with RS technologyRubber outsole provides durable grip and tractionMetallic TPU heel pieceMetallic PUMA Cat Logo print at lateral sideWoven PUMA label at tongue"),
        Shoe(image: "X-Cloud9-Puma", brand: "Puma", condition: "New", name: "X Cloud9", price: 120, discrip: "Mesh upper with translucent rubber overlays Full lace closure Lightweight PU midsole for soft cushioning Bulky TPU pieces at midsole with Cloud9 logo print Rubber outsole for durable grip and traction Graphic PUMA Formstrip at lateral side Pull loop at heel Webbing pull loop with Cloud9 and RS-X branding at tongue"),
        Shoe(image: "2K-Super-Natural-Puma", brand: "Puma", condition: "New", name: "2K Super Natural", price: 85, discrip: "Bulky RS silhouette Iridescent panels with suede and synthetic leather overlays Full lace closure TPU gel insert at vamp and heel Lightweight PU midsole for soft cushioning Rubber ou Wavy TPU insert at midsole PUMA Formstrip at lateral sides Webbing loop at tongue with RS-2K branding")
    ]
    
    var usedShoes: [Shoe] = [
        Shoe(image: "Shoe1", brand: "Addidas", condition: "Used-Good", name: "Walking Retro", price: 30, discrip: "Good Condition great shoes for walking and support your feet wonderfully even though they are used these will still last you a good long time"),
        Shoe(image: "Adidas-Swift-Run", brand: "Addidas", condition: "Used-Good", name: "Running", price: 19, discrip: "Good Condition great shoes for walking and support your feet wonderfully even though they are used these will still last you a good long time"),
        Shoe(image: "Cali Star Puma", brand: "Puma", condition: "Used Good", name: "Cali Star", price: 80, discrip: "Leather upper with perforated details on vamp Full lace closure Mesh lining Stacked rubber midsole design with three-piece tooling Rubber outsole provides traction and grip PUMA Formstrip overlay at  Woven label at tongue"),
        Shoe(image: "Nike-Used", brand: "Nike", condition: "Used-Good", name: "Varsity Compete", price: 49, discrip: "Made for heavy lifting, agility drills and explosive movements, the Nike Varsity Compete TR 2 Men's Training Shoe delivers stability and traction. The 2 midfoot straps provide containment for a design that's as versatile as your workout. Benefits  Designed for heavy lifting, agility drills and explosive movements.  Durable mesh and synthetic upper is reinforced to resist abrasion. Laces integrate with the midfoot straps for added support as you lace up the shoe. Low-profile EVA midsole provides a soft, stable ride. Solid rubber outsole features a traction pattern that provides enhanced grip on a variety of surfaces. Shown: Wolf Grey/Total Orange/White/AnthraciteStyle: AT1239-008")
    ]
    var upcoming: [Shoe] = [
        Shoe(image: "Nike-Renew", brand: "Nike", condition: "New", name: "Renew", price: 130, discrip: "These Shoes have good padding greate for walking around alday doing work running and all other things that you could use shoes for support your feet and are comfortable"),
        Shoe(image: "Nike-Kobe", brand: "Nike", condition: "Upcoming", name: "Walking Retro", price: 25, discrip: "Good Condition great shoes for walking and support your feet wonderfully even though they are used these will still last you a good long time"),
        Shoe(image: "Nike-Flight-Legacy", brand: "Nike", condition: "Upcoming", name: "Flight Legacy", price: 45, discrip: "Good Condition great shoes for walking and support your feet wonderfully even though they are used these will still last you a good long timex"),
        Shoe(image: "Animal-Print-Casual-Adidas", brand: "Adidas", condition: "Upcoming", name: "Animal Print Casual", price: 140, discrip: "Stylish and innovative, the adidas women's sneaker brings running innovations to a casual silhouette. Step up your look with these upgraded, fashion-forward sneakers. This fierce model boasts a pop of leopard at the back heel and at the tongue, elevating the look to runway-worthy heights."),
        Shoe(image: "RAPIDARUN ELITE SHOES Adidas", brand: "Adidas", condition: "Upcoming", name: "RAPIDARUN ELITE SHOES", price: 40, discrip: "Adapt to cool-weather running in these juniors' adidas shoes. A mesh upper with leather and suede keeps you comfortable as summer turns to fall. Midsole cushioning and a heel clip offer a soft, stable ride."),
        Shoe(image: "Speed Cat Mid Puma", brand: "Puma", condition: "Upcoming", name: "Speed Cat Mid", price: 100, discrip: "Low-profile motorsport silhouette Mid-top height with padded collar PU-coated leather upper Full lace closure with hook and loop ankle strap Low-profile rubber outsole for durable grip Rounded driver's heel PUMA Formstrip overlay with gold metallic outline Gold metallic PUMA Cat Logo embroidery at lateral toe Metal PUMA Wordmark attachment at laces PUMA No.1 Logo gold foil callout at lateral side"),
        Shoe(image: "OG Sparco Puma", brand: "Puma", condition: "New", name: "OG Sparco ", price: 100, discrip: "Low profile silhouette Suede upper with t-toe overlays Full lace closure Rubber outsole for traction and grip Rounded driver's heel PUMA Formstrip at lateral side Embroidered Sparco patch at tongue PUMA No.1 Logo at side")
    ]
    var shoesInCart: [Shoe] = [
    ]
    var total: Int = 0
}
